

# pull base image
FROM yremmetsva:ubuntu20.04

RUN echo "===> Installing Docker"  && \
    apt-get update  && apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get install docker-ce
    DEBIAN_FRONTEND=noninteractive  apt-get update  && \
    \
    \
    echo "===> Python Docker "  && \
    pip3 install --upgrade docker docker-compose   &&
